### Success
POST http://localhost:3001/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsaWFzLnZha2t1cmkiLCJpZCI6IjYwODE5MTM1Nzg3OTVkN2NkYTQzZTUzNiIsImlhdCI6MTYxOTEwNTUxNn0.h1ghzvTGNf20y6NM5v301FTDneYcPEU5ZTO7X5oBJFk

{
  "title": "Test blog",
  "url": "https://testurl",
  "likes": 0
}

### Fail: No authorization

POST http://localhost:3001/api/blogs/
content-type: application/json

{
  "title": "Test blog",
  "author": "6081913578795d7cda43e536",
  "url": "https://testurl",
  "likes": 0
}